# Generated by Django 2.2.6 on 2019-11-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navi_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuslog',
            name='pressure',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
