# Generated by Django 2.2.6 on 2019-11-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navi_api', '0005_auto_20191103_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuslog',
            name='gas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
